### ISSUE TITLE
Add conference tag

### ISSUE THREAD

**Issue by ineiti** [c4dt/showcase#120]
The paper-entry should have an additional conference tag where one can link to the conference the paper has been published.

**Comment by cgrigis** [comment]
To make sure I understand correctly, this should look something like this (example for `omniledger`):

----
(...)
Papers:
* [Enhancing Bitcoin performance](https://www.usenix.org/system/files/conference/usenixsecurity16/sec16_paper_kokoris-kogias.pdf) — published at: [25th USENIX Security Symposium](https://www.usenix.org/conference/usenixsecurity16)
----

with the paper link being the one hosted at the conference, and the conference link pointing to the general conference.
* Is that correct?
* Should we also add this information to the `incubator` and `demo` pages?
* Do we also want something similar for publications in journals, e.g. _IEEE Transactions on Information Forensics and Security_?

**Comment by ineiti** [comment]
yes, this looks good. I would also add it to the `incubator` and `demo` pages. Of course it should suit all kind of publication targets. Not sure whether this should even be a list... Something like:

```yaml
        information:
            - type:   Paper
              title:  'ClaimChain: Improving the Security and Privacy of In-band Key Distribution for Messaging'
              url:    https://arxiv.org/abs/1707.06279
              publication:
                - name: 25th USENIX Security Symposium
                   url: https://
                - name: Something else
                   url: https://                   
```

Man, I hate writing yaml without formatting support in the editor...
