### ISSUE TITLE
Create entry for Orchard

### ISSUE THREAD

**Issue by ineiti** [c4dt/showcase#335]
Please add an entry to the showcase for the Orchard project. It should have the following content:
- short description
- the `incubator` field:
```yaml
    incubator:
      work: (What C4DT did for the project)
      products:
        type: ( Demo | Hands-on | Pilot | App | OSS-participation)
        url: (https://...)
        title: (Description of this product)
```
